### ISSUE TITLE
Error in Bigram_wiki.ipynb

### ISSUE THREAD

**Issue by Gunnvant** [anujgupta82/Representation-Learning-for-NLP#3]
While executing cell 6 in this notebook, which seems to be calling `get_wiki_data(),` `"too many values to unpack" `exception is raised. I tried this notebook in the image shared during workshop.

The notebook is in `module2/BiGram/`

**Comment by anujgupta82** [comment]
@Gunnvant : my notebook runs fine.  Can you do `git pull -r` and try and run it again ?
